#ifndef INITIALIZATION
#define INITIALIZATION

#define RED_PIN 9
#define FIRST_GREEN_PIN 10
#define SECOND_GREEN_PIN 11
#define THIRD_GREEN_PIN 12
#define FOURTH_GREEN_PIN 13

#define LEDS_NUMBER 4

#define FIRST_BUTTON_PIN 2
#define SECOND_BUTTON_PIN 3
#define THIRD_BUTTON_PIN 4
#define FOURTH_BUTTON_PIN 5

#define POTENTIOMETER_PIN A0

#define STANDBY_TIME 10000
#define MAX_NUMBER 15
#define T1_TIMER 20000
#define DEBOUNCE_TIME 300
#define FIRST_ROUND_TIME 15000

#define SCORE_INCREASE 100
#define BASE_FACTOR 1

#define MIN_DIFFICULTY 1
#define MAX_DIFFICULTY 4

typedef enum States{START, SLEEP, GAME } state; 

#endif
